"""create matakuliah tabel

Revision ID: 103829bf1520
Revises: ca43dd31ef3e
Create Date: 2025-11-21 17:42:55.056130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103829bf1520'
down_revision = 'ca43dd31ef3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
